name: Run Script

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install sdkman
        shell: bash -i {0}
        run: curl -s "https://get.sdkman.io" | bash
      - name: Install kotlin
        shell: bash -i {0}
        run: sdk install kotlin
      - name: Install kscript
        shell: bash -i {0}
        run: sdk install kscript
      - name: Run script
        shell: bash -i {0}
        run: kscript scaffolded-script.kts
      - name: Bundle script
        shell: bash -i {0}
        run: kscript --package scaffolded-script.kts

      - uses: actions/upload-artifact@v1
        with:
          name: scaffolded-script
          path: ./scaffolded-script
